#!/bin/bash
# $Id: arcmail,v 1.5 2015/05/15 14:40:07 fulford Exp fulford $
# $Source: /src/merlin/usr/local/etc/RCS/arcmail,v $
# $Revision: 1.5 $
# Author C W Fulford.
# Copyright 2015 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0709 229 5385
########################################################################
cmd=`basename $0`
ver=`echo "$Id: arcmail,v 1.5 2015/05/15 14:40:07 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [[-c <configfile>] [-d] [-l] [-m <max>] [-v] <email_address>]|[-V]"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0;shift;;
		-l) log=:; shift;;
		-m) clmax=$2;shift 2;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.5 $ $Date: 2015/05/15 14:40:07 $"|awk '{print $1,$3,$6}';exit;;  
		 *@*) ma=$1;shift ;;
	 	 *) echo "$syntax">&2; exit 1;;
	esac
done


[ "$ma" ] ||{ echo "$syntax" >&2;exit 1;}
expr "$ma" : ".*@[^\.]*\.[^\.]*">/dev/null ||{
	echo "$ma is not a valid e-mail address" >&2
	exit 1
}
md=`echo $ma|awk -F@ '{print $2}'`
getent hosts $md 2>&1 >/dev/null ||{
	echo "$cmd can't find IP address for $md">&2 
	exit 1 
}  
[ "$verbose" ]&& echo "$cnd: connecting to $ma"
mu=`echo $ma|awk -F@ '{print $1}'`

config=${config:-/usr/local/etc/${cmd}.cf}
[ -r $config ] ||{ echo  "$cmd: Can\'t find $config"; exit 1 ;}
sed <$config -ne "/^$md:/,/^$/{/^[\t ]*[^#].*=.*/p}"
eval `sed <$config -ne "/^$md:/,/^$/{/^[\t ]*[^#].*=.*/p}"`

max=${max:-5000}
max=${clmax:-$max}
basedir=${basedir:-/var/qmail/mailnames}
maildir=$basedir/$md/$mu/Maildir
archf=$maildir/.Archive
proto=${proto:-ssh}
tmp=/tmp/$cmd$$

if [ "$proto" == "ssh" ] ;then
	c=`ssh $md "sudo bash -c \"cd $maildir/cur;ls -lt\""|
		tee $tmp|wc -l`
	[ $c -le $max ] && {
		echo "$cmd: $mu has $c messages only" >&2
		exit 1
	}
	f=`expr $max + 1`
	echo "$cmd: moving `expr $c - $max` messages."
	cat $tmp|sed -ne ''$f',$p'|awk '{print $8}'|uniq|
	while read yr;do
		archive=$archf.$yr
		ssh $md "sudo bash -c \"
			[ -d $archf ] ||{
				mkdir -m 700 $archf
				chown -R popuser.popuser $archf
			}
			[ -d $archive ] ||{
		       		mkdir -p -m 700 $archive/{cur,new,tmp}
				touch $archive/maildirfolder
				chmod 600 $archive/maildirfolder
				chown -R popuser.popuser $archive
			}\""
	done
	cat $tmp|sed -ne ''$f',$p'|
	awk '{printf("ssh '$md' sudo mv '$maildir'/cur/"$9 " '$archf'."$8"/cur")|"sh";close("sh");c[$8]++}' 
	etot=|ssh $md "sudo find $maildir/cur" wc -l
	mtot=`expr $tot - $etot`
fi
[ "$verbose" ]&& echo "cmd: $mtot messages archived for $ma."
[ "$log" ]&& logger -t cmd "$mtot messages archived for $ma"

