.TH ARCMAIL 8l "14th May 2015 r1.41
.SH NAME
.B arcmail
- moves old mail from a users current Maildir mailbox. The mail is sorted
into annual archive folders. 
.SH SYNOPSIS
\fBarcmail\fR
[\fB-c \fI<config_file>\fR]
[\fB-d\fR]
[\fB-l \fR]
[\fB-m \fI<max>\fR]
[\fB-n \fR]
[\fB-v \fR]
\fI<mail_account>\fR |
[\fB-V \fR]
.br
.SH AVAILABILITY
.B arcmail
is a Bourne shell script which should work equally well on all versions of UNIX,
Linux and Mac OS X.
.SH DESCRIPTION
.B arcmail
uses "\fBssh\fR"
to connect to a 
.B postfix 
mail server to archive mail where the number of messages held in and INBIX
exceeds the prescribed limit. 
.LP
The limit may be set on the command line or in the configuration file. (The
default limit is 5000). 
.LP
The oldest messages are sorted by the year of last modification and 
are deposited in annualised subfolders of "\fI.Archive\fR". E.g.
"\fI.Archive.2014\fR".
.LP
The script was developed to assist a client company which experiencing perfomance
problems with INBOXes with some key workers holding in excess of 14,000 messages
in their INBOX. For legal reasons the company was anxious to retain access to all
old e-mail. By using unsubscribed archive folders the burdon on the IMAP server
and the local Apple e-mail clients is much reduced while still retaining 
occasional access via webmail (using 
.B Horde
in this instance). Access by the usual mail client is still available at a pinch
but the burden on both client and server is much reduced.
.LP
If the archive folders do not exist they are created as required by the 
script.
.B NB .
The script expects that the administrator will have 
.B ssh 
access to the mail server and will be able to use
.B sudo
to obtain superuser privileges.
.SH OPTIONS
.TP 5
.B -c
Use the specified configuration file in preference to the default
\fI"/usr/local/etc/arcmail.cf"\fR.
If no configuration file is found the script will print an error message to
screen and will terminate.
.IP
Options set on the command line supercede those found in the 
.I config
file.
.TP 5
.B -d
Set debug mode on. 
The \fB-x\fR option is set within the shell
and each command in the script is echoed to the console.
.TP 5
.B -l
Use the local syslog facility to log that the check has been made and 
record the number of messages returned.
.TP 5
\fB-m \fI<max>\fR
Messages in excess of the 
.I maximum
theshold will be moved to the 
.I .Archive
subfolders.
.TP 5
\fB-n\fR
.I <mail_addr>
.IP
Notifications of the number of messages moved will be sent to "
.IR mail_addr ".
.TP 5 
.B -v
Set verbose mode on. 
.TP 5
.I <mail_address> 
If the mail domain cannot be resolved then an error message is printed and
the script exits.
.IP
The mail domain name and mail user name is used to find the path to the
INBOX current folder on the remote server.
.IP
The base directory is expected to be "\fI/var/qmail/mailnames/\fR" but this
may be set in the
.I config
file.
.TP 5
.B -V
Print the version details and exit. 
.SH FILES
.IR arcmail.cf .
.SH EXAMPLES
.IP
.nf
.ft CW
arcmail -v -l -m 500 fulford@fulford.net 
.ft R
.fi
.LP
If "\fIfulford.net\fR" can be successfully resolved a 
.B ssh
connection is made to the host and the number of messages in
\fI/var/qmail/mailnames/fulford.net/fulford/Maildir/cur\fR
are counted.
.LP
If the total exceeds the maximum of 500 set with the 
.B -m
option the oldest messages will sorted by the year of last change and
moved to mailboxes designated
.IR .Archive.2013,
.IR .Archive.2014 ,
.I .Archive.2015
etc.
.SH SEE ALSO
.IR chkmail ,
.IR lsbounced ,
.IR msg_cnt ,
.IR msg_del .
.SH AUTHOR
Clifford W Fulford, City Linux. Contact fulford@fulford.net or +44 (0)709 229 5385.
.SH HISTORY
